services:

 redis:
  image: redis:7-alpine
  platform: linux/arm64
  ports:
   - "6379:6379"

 redis-commander:
  image: rediscommander/redis-commander:latest
  environment:
   - REDIS_HOSTS=local:redis:6379
  ports:
   - "8081:8081"
  depends_on:
   - redis

 qdrant:
  image: qdrant/qdrant:latest
  platform: linux/arm64
  ports:
   - "6333:6333"
   - "6334:6334"
  volumes:
   - qdrant_data:/qdrant/storage

volumes:
 qdrant_data:
